### Default String Configuration
### Add custom strings in custom/strings.yaml

# base config in partials/branding, partials/head
branding:
  name: SNU VDCL 정보공유 플랫폼
  prettyName: SNU VDCL Library
  org: VDCL
  icon: /assets/images/icon-logo.svg
  favicon: /assets/images/library.ico

# pages/categories, pages/index, partials/search
landing:
  tagline: 연구실 최신 자료를 한곳에!
  viewAll: 모든 문서 보기
  quickLink: <a href="http://vdcl.snu.ac.kr">VDCL 홈페이지</a>
  modules:
    - tag: 팀
      label: 팀별로 보기
      style: button
    - tag: README
      label: 기본적인 이용 안내
      style: docs


# partials/footer
footer:
  helpText: 문제 발생이나 기타 문의는 관리자(이현성)에게 갠톡 주세요
  defaultEmail: user@your_organization.com
  buttons:
    edit: 페이지 수정
    move: 페이지 이동
    create: 새 페이지
    viewFolder: 폴더 보기

# pages/search, partials/search
search:
  placeholder: Search...
  results:
    title: !!js/function (query) => `Search results for ${query}`
    kicker: !!js/function (query) => `Showing results for '${query}':`
    label:
      folder: !!js/function (path, folder) => `Filed under <a class="folder" href=${path}><span>${folder}</span></a>`
      person: !!js/function (lastUser) => `Last edited by <span class='author'>${lastUser}`
    none:
      kicker: !!js/function (query) => `There are no results for '${query}'`
      suggestion: To request a new page, contact your administrators.

# categories/default
folder:
  childrenList:
    kicker: !!js/function (title) => `Pages in ${title}`
  # partials/sectionList
  sectionList:
    heading: "Table of Contents:"
  #partials/siblingList
  siblingList:
    heading: Related Docs

# playlists/default
playlist:
  childrenList:
    kicker: !!js/function (title) => `${title} Playlist`
  siblingList:
    heading: !!js/function (title) => `${title} Playlist`
  nav:
    previous: <
    next: '>'

# errors
error:
  403:
    title: Operation Not Permitted
    heading: 허용되지 않은 접근입니다. (Not Authorized)
    message: "<p>접근 권한이 없습니다. 다른 계정으로 로그인하시거나 관리자에게 접근 권한을 요청하세요.</p>"
  404:
    title: Page Not Found
    heading: 없는 페이지입니다. (404)
    message: 다른 페이지를 찾아보세요.
  500:
    title: Server Error
    heading: 서버 에러가 발생하였습니다. (500)
    message: 다시 시도해보고 문제 지속시 관리자에게 연락하세요.

# warning messages
warning:
  duplicate: !!js/function (names, folderId) => `Multiple resources in <a href="https://drive.google.com/drive/u/0/folders/${folderId}" target="_blank">this folder</a> share the same name&#58; ${names.join(', ')}. Only one will be accesible through Library.`
